name: pagination_view
description: Flutter package to simplify pagination of list of items from the internet.
version: 1.0.0
homepage: https://github.com/excogitatr/pagination_view

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  effective_dart: ^1.2.1

  # Testing
  bloc_test: ^5.0.0
  mockito: ^4.1.1
