name: pagination_view
description: Flutter package to simplify pagination of list of items from the internet.
version: 1.0.3+2
issue_tracker: https://github.com/excogitatr/pagination_view/issues
homepage: https://github.com/excogitatr/pagination_view

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  effective_dart: ^1.3.0

  # Testing
  bloc_test: ^7.1.0
  mockito: ^4.1.4
